apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-py-app
spec:
  replicas: 3
  selector:
    matchLabels:
      role: sample-py-app
  template:
    metadata:
      labels:
        role: sample-py-app
    spec:
      containers:
      - name: sample-py-app
        image: gbt55/sample-py-app:v1.0.17
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Madrid
---
apiVersion: v1
kind: Service
metadata:
  name: sample-py-app
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    role: sample-py-app
  type: ClusterIP
